servicemonitor crud接口
TencentBlueKing/bk-bcs pull request #2062
Opened 2023-03-27 09:17 UTC by yaoxinwang-git

1.bcs-monitor 添加servicemonitor crud接口
2.servicemonitor结构体来源于github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring v0.46.0 高版本对gomod文件修改较多

https://github.com/TencentBlueKing/bk-bcs/issues/2032

2023-03-27 09:17 UTC, tencentblueking-adm commented
[![CLA assistant check](https://bk-cla.bktencent.com:443/pull/badge/signed)](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-bcs?pullRequest=2062) <br/>All committers have signed the CLA.

2023-03-28 04:14 UTC, adevjoe requested changes

2023-03-28 04:14 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/api/routes.go
> +		route.GET("/service_monitors/namespaces/:namespace",
`/namespaces/:namespace` 要放在前面，遵循 restful 风格

2023-03-28 04:14 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/api/routes.go
> +		route.POST("/service_monitors/update/namespaces/:namespace/servicemonitors/:name",
`name` 放在 body 里面，路径可以是 `/namespaces/:namespace/service_monitors`，路径里面不需要动词

2023-03-28 04:14 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/api/routes.go
> +		route.POST("/service_monitors/create/namespaces/:namespace/servicemonitors/:name",
同更新接口

2023-03-28 04:14 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/api/routes.go
> +		route.DELETE("/service_monitors/batchdelete",
batchdelete 因为有 body，不要用 DELETE，根据规范这里用 POST

2023-03-28 04:14 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/api/servicemonitor/servicemonitor.go
> +func calcIamNsId(clusterId string, namespace string) (string, error) {
https://github.com/TencentBlueKing/bk-bcs/blob/master/bcs-services/pkg/bcs-auth/utils/utils.go#L173

可以用这个函数

2023-03-28 04:14 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/api/servicemonitor/servicemonitor.go
> +	clusterMap, err := service_monitor.ListClusters(projectId, limit, offset)
不需要校验集群

2023-03-28 04:14 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/api/servicemonitor/servicemonitor.go
> +	handleServiceMonitorItems(clusterId, clusterMap, namespaceMap, serviceMonitors)
直接返回 serviceMonitor 列表就可以了，不需要特殊处理，和详情接口一样

2023-03-28 04:14 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/component/service_monitor/servicemonitor.go
> +func CreateServiceMonitor(namespace string, spec *ServiceMonitor) (*ServiceMonitor, error) {
servicemonitor 的接口不用单独封装，直接用 [prometheus-operator](https://github.com/prometheus-operator/prometheus-operator/blob/main/pkg/client/versioned/clientset.go) 提供的 client 就可以

2023-03-31 07:20 UTC, adevjoe requested changes

2023-03-31 07:20 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/api/servicemonitor/servicemonitor.go
> +	kubeConf, err := clientutil.GetKubeConfByClusterId(clusterId)
配置文件不同，这是不能直接调用 `bcs-unified-apiserver` 的 `GetKubeConfByClusterId ` 方法

2023-03-31 07:20 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/api/routes.go
> +		route.PUT("/namespaces/:namespace/service_monitors",
PUT 带上 `:name`

2023-03-31 07:20 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/api/servicemonitor/servicemonitor.go
> +	serviceMonitor.APIVersion = "monitoring.coreos.com/v1"
APIVersion 和 kind 不用设置，默认就有了

2023-03-31 07:20 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/api/servicemonitor/servicemonitor.go
> +	//更新会合并 selector，因此先删除, 再创建
为什么要删除，直接覆盖更新应该就可以吧

2023-04-04 02:30 UTC, adevjoe approved these changes

2023-04-06 03:37 UTC, adevjoe approved these changes

2023-04-06 03:51 UTC, ifooth approved these changes

2023-04-06 03:51 UTC, merged