bcs-helm-manager新增watch白名单相关配置
TencentBlueKing/bk-bcs pull request #2070
Opened 2023-04-03 02:14 UTC by Ambition9186

- 白名单相关配置采用 watch 形式，单独一份白名单配置文件，能动态配置白名单
- 相关issue：https://github.com/TencentBlueKing/bk-bcs/issues/2064

2023-04-04 02:23 UTC, adevjoe approved these changes

2023-04-04 02:23 UTC, adevjoe commented on bcs-services/bcs-helm-manager/internal/app/app.go
> +			if string(value.Bytes()) == "null" {
什么情况会传入 null

2023-04-04 02:41 UTC, adevjoe requested changes

2023-04-04 02:41 UTC, adevjoe commented on bcs-services/bcs-helm-manager/internal/app/app.go
> +			err = json.Unmarshal(value.Bytes(), &cred)
这里需要 yaml 格式的配置文件

2023-04-04 02:41 UTC, adevjoe commented on bcs-services/bcs-helm-manager/internal/app/app.go
> +			if string(value.Bytes()) == "null" {
直接在下面 `Unmarshal` 一起判断是不是就可以，因为 `null` 是非法的，就不会真实解析。不用单独判断了

2023-04-17 06:28 UTC, adevjoe approved these changes
LGTM

2023-04-17 07:16 UTC, ifooth approved these changes

2023-04-17 07:16 UTC, merged