bcs-common新增gin tracing中间件
TencentBlueKing/bk-bcs pull request #2104
Opened 2023-04-14 08:08 UTC by Ambition9186

- bcs-common新增gin tracing中间件
- 打印请求和响应数据，支持路由过滤

2023-04-17 06:31 UTC, adevjoe commented
没编译过，依赖需要执行一下 `go mod tidy -go=1.16 && go mod tidy -go=1.17`

2023-04-20 01:54 UTC, adevjoe requested changes

2023-04-20 01:54 UTC, adevjoe commented on bcs-common/pkg/otel/trace/gin/middleware.go
> +		spanName := c.FullPath()
这里能不能获取属于哪个 route，而不是真实访问的路径，比如 `/user/:id`，而不是 `/user/1`，不要包含参数。参考 https://uptrace.dev/opentelemetry/distributed-tracing.html#span-names

2023-04-20 01:54 UTC, adevjoe commented on bcs-common/pkg/otel/trace/gin/middleware.go
> +func Middleware(server string, opts ...Option) gin.HandlerFunc {
gin 中间件可以参考 https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/github.com/gin-gonic/gin/otelgin

2023-04-20 01:54 UTC, adevjoe commented on bcs-common/pkg/otel/trace/gin/middleware.go
> +		var params string
query 和 body 单独记录吧，不用区分 method

2023-04-20 06:31 UTC, adevjoe approved these changes

2023-04-23 07:43 UTC, ifooth approved these changes

2023-04-23 07:43 UTC, merged