bcs-helm-manager cli开发
TencentBlueKing/bk-bcs pull request #2108
Opened 2023-04-19 08:58 UTC by yaoxinwang-git

1.bcs-helm-manager cli开发
2.提供cli README.md

2023-04-19 09:36 UTC, adevjoe requested changes

2023-04-19 09:36 UTC, adevjoe commented on bcs-services/bcs-helm-manager/internal/client/README.md
> +### 获取Chart列表V1版 - ListChartV1
这些有 v1 的都不用特别注明 v1了，v1 主要是为了区分之前的老版本，文档和命令都可以把 v1 去掉。

2023-04-19 09:36 UTC, adevjoe commented on bcs-services/bcs-helm-manager/internal/client/cmd/upgradev1.go
> +	upgradeV1CMD.PersistentFlags().StringVarP(
sysvar 不需要传，现在没这些参数了

2023-04-21 06:44 UTC, adevjoe approved these changes

2023-04-23 07:43 UTC, ifooth approved these changes

2023-04-23 07:43 UTC, merged