新增用户查询接口
TencentBlueKing/bk-bcs pull request #2121
Opened 2023-04-23 08:01 UTC by LidolLxf

- 新增用户查询接口

2023-04-23 08:01 UTC, tencentblueking-adm commented
[![CLA assistant check](https://bk-cla.bktencent.com:443/pull/badge/not_signed)](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-bcs?pullRequest=2121) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-bcs?pullRequest=2121) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bk-cla.bktencent.com:443/check/TencentBlueKing/bk-bcs?pullRequest=2121) it.</sub>

2023-04-23 09:24 UTC, adevjoe requested changes

2023-04-23 09:24 UTC, adevjoe commented on bcs-services/bcs-user-manager/app/user-manager/v1http/router.go
> +	ws.Route(auth.AuthFunc(ws.GET("/v1/users/info")).To(user.GetCurrentUserName))
放到 `initTokenRouters` 路由里面吧，initUsersRouters 目前没开放给用户态用，path 还可以用 `/v1/users/info`

2023-04-23 09:24 UTC, adevjoe commented on bcs-services/bcs-user-manager/app/user-manager/v1http/auth/auth.go
> +		request.SetAttribute(constant.CurrentUserAttr, user)
这里就不需要了

2023-04-23 10:18 UTC, adevjoe approved these changes
LGTM

2023-04-23 10:18 UTC, adevjoe commented on bcs-services/bcs-user-manager/app/user-manager/v1http/router.go
> +	ws.Route(auth.TokenAuthFunc(ws.GET("/v1/users/info")).To(user.GetCurrentUserName))
改成 `GetCurrentUserInfo` 贴切一点

2023-05-08 07:48 UTC, ifooth approved these changes

2023-05-08 07:48 UTC, merged