修复自定义Ingress资源返回panic问题
TencentBlueKing/bk-bcs pull request #2203
Opened 2023-05-16 08:02 UTC by Ambition9186

- 修复自定义Ingress资源返回panic问题

2023-05-16 10:09 UTC, adevjoe requested changes

2023-05-16 10:09 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/resource/formatter/common.go
> +	if kind == "Ingress" && apiVersion == "networkextension.bkbcs.tencent.com/v1" {
kind 和 apiVersion 这两个值添加到常量里面吧，`pkg/resource/constants/conmon.go`

2023-05-17 03:37 UTC, adevjoe approved these changes
LGTM

2023-05-18 11:28 UTC, ifooth approved these changes

2023-05-18 11:28 UTC, merged