bcs-monitor配置文件优化
TencentBlueKing/bk-bcs pull request #2228
Opened 2023-05-24 08:31 UTC by Ambition9186

- 精简配置文件
- 新增打印配置文件

2023-05-24 08:56 UTC, adevjoe requested changes

2023-05-24 08:56 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/api/servicemonitor/servicemonitor.go
> +	bcsConf := k8sclient.GetBCSConfByClusterId()
直接 `GetBCSConf`，没有 clusterId 了

2023-05-25 09:48 UTC, adevjoe requested changes

2023-05-25 09:48 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/api/servicemonitor/servicemonitor.go
> +	host := fmt.Sprintf("%s/clusters", bcsConf.Host)
`host := fmt.Sprintf("%s/clusters", bcsConf.Host)` 这里拼接还是需要 clusterid 的，这一行不用修改。

2023-05-25 10:15 UTC, adevjoe approved these changes

2023-05-26 03:15 UTC, adevjoe approved these changes

2023-05-26 03:27 UTC, adevjoe requested changes

2023-05-26 03:27 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/component/k8sclient/helper.go
> +// GetBCSConfBy 返回BCS配置
这里的注释开头要改成 `GetBCSConf`，和函数名一样

2023-05-26 03:27 UTC, adevjoe commented on bcs-services/bcs-monitor/cmd/bcs-monitor/root.go
> +func ConfigViewCmd() *cobra.Command {
导出的函数需要添加注释，可以装一个 lint 插件

2023-05-31 12:14 UTC, adevjoe approved these changes

2023-06-01 10:11 UTC, ifooth approved these changes

2023-06-01 10:11 UTC, merged