cluster-resources 优化workload和pod列表 返回request/limit数据
TencentBlueKing/bk-bcs pull request #2236
Opened 2023-05-26 09:22 UTC by Ambition9186

- pod列表接口数据精简
- 所有workload列表返回requests/limits

2023-06-01 09:44 UTC, adevjoe requested changes

2023-06-01 09:44 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/resource/formatter/workload.go
> +	for _, r := range containers {
这里可以一起解析，spec.containers 是一个数组

2023-06-01 09:44 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/resource/formatter/common.go
> +		newManifest = map[string]interface{}{"kind": mapx.GetStr(manifest, "kind"), "apiVersion": mapx.GetStr(manifest, "apiVersion"), "metadata": metadata}
太长了，限制 120 个字符

2023-06-01 09:44 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/resource/formatter/workload.go
> +	"github.com/TencentBlueKing/gopkg/collection/set"
`"github.com/TencentBlueKing/gopkg/collection/set"` 外部包移到上一段

2023-06-05 07:34 UTC, adevjoe requested changes

2023-06-05 07:34 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/resource/formatter/workload.go
> +		log.Info(context.TODO(), "JSON marshaling error:: %s", err)
出错要直接返回，不要继续下面的逻辑，log 类型要 Error

2023-06-05 07:34 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/resource/formatter/workload.go
> +		log.Info(context.TODO(), "JSON unmarshaling error:: %s", err)
同上

2023-06-07 12:18 UTC, adevjoe approved these changes

2023-06-14 07:04 UTC, ifooth approved these changes

2023-06-14 07:04 UTC, merged