node/overvie和clusters/overview新增pod_total
TencentBlueKing/bk-bcs pull request #2255
Opened 2023-06-02 07:55 UTC by Ambition9186

- node/overvie和clusters/overview新增pod_total

2023-06-05 07:58 UTC, adevjoe requested changes

2023-06-05 07:58 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/storegw/bcs_system/source/bk_monitor/cluster.go
> +	pods, err := k8sclient.GetPodListContainers(ctx, clusterId, "", "")
`GetPodListContainers ` 是获取集群中运行的pod 数，需求是获取节点最大允许 pod 数，要从 node 信息中获取，`status.allocatable.pods`

2023-06-05 07:58 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/api/metrics/cluster.go
> +		"pod_total": `bcs:cluster:pod:total{cluster_id="%<clusterId>s", %<provider>s}`,
要注意 lint

2023-06-05 08:13 UTC, adevjoe requested changes

2023-06-05 08:13 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/storegw/bcs_system/source/federation/cluster.go
> +func (p *Federation) GetClusterPODUsed(ctx context.Context, projectId, clusterId string, start, end time.Time, step time.Duration) ([]*prompb.TimeSeries, error) {
加上注释

2023-06-05 08:13 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/storegw/bcs_system/source/federation/cluster.go
> +func (p *Federation) GetClusterPODTotal(ctx context.Context, projectId, clusterId string, start, end time.Time, step time.Duration) ([]*prompb.TimeSeries, error) {
加上注释

2023-06-05 08:13 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/storegw/bcs_system/source/compute/cluster.go
> +func (p *Compute) GetClusterPODUsed(ctx context.Context, projectId, clusterId string, start, end time.Time, step time.Duration) ([]*prompb.TimeSeries, error) {
加上注释

2023-06-05 08:13 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/storegw/bcs_system/source/compute/cluster.go
> +func (p *Compute) GetClusterPODTotal(ctx context.Context, projectId, clusterId string, start, end time.Time, step time.Duration) ([]*prompb.TimeSeries, error) {
加上注释

2023-06-05 08:13 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/storegw/bcs_system/source/compute/cluster.go
> +	//TODO implement me
TODO 注释可以去掉了，不然流水线扫描会不过

2023-06-07 12:09 UTC, adevjoe requested changes

2023-06-07 12:09 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/component/k8sclient/pod.go
> +func GetPodListContainers(ctx context.Context, clusterId string) ([]v1.Node, error) {
函数名和内容不符

2023-06-07 12:09 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/component/k8sclient/pod.go
> +func GetNodePod(ctx context.Context, clusterId, nodeName string) (*v1.Node, error) {
函数名和内容不符

2023-06-07 12:09 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/storegw/bcs_system/source/base/base.go
> +	GetClusterPODUsed(ctx context.Context, projectId, clusterId string, start, end time.Time,
`Pod` 名称统一，PR 里面的都改成 `Pod`

2023-06-07 12:09 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/storegw/bcs_system/source/bk_monitor/cluster.go
> +	return []*prompb.TimeSeries{{Samples: sample}}, nil
生成 Series 可以参考这个函数
```go
func GetSameSeries(start, end time.Time, step time.Duration, values float64,
	labels []prompb.Label) []*prompb.TimeSeries {
	result := &prompb.TimeSeries{
		Labels:  labels,
		Samples: make([]prompb.Sample, 0),
	}
	if step == 0 {
		return []*prompb.TimeSeries{result}
	}
	for cur := start; cur.Before(end); cur = cur.Add(step) {
		result.Samples = append(result.Samples, prompb.Sample{
			Value:     values,
			Timestamp: cur.UnixMilli(),
		})
	}
	return []*prompb.TimeSeries{result}
}
```

2023-06-07 12:09 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/storegw/bcs_system/source/bk_monitor/cluster.go
> +		Timestamp: start.UnixMilli(),
时间戳需要变化，按 step 增加

2023-06-07 12:09 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/storegw/bcs_system/source/bk_monitor/node.go
> +	return []*prompb.TimeSeries{{Samples: sample}}, nil
同上

2023-06-07 12:09 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/storegw/bcs_system/source/compute/cluster.go
> +func (p *Compute) GetClusterPODUsed(ctx context.Context, projectId, clusterId string, start, end time.Time, step time.Duration) ([]*prompb.TimeSeries, error) {
注意代码长度，不长于 120 个字符

2023-06-08 08:27 UTC, adevjoe requested changes

2023-06-08 08:27 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/storegw/bcs_system/source/base/base.go
> +func GetSameSeries(start, end time.Time, step time.Duration, values float64,
添加注释

2023-06-08 08:30 UTC, adevjoe approved these changes

2023-06-14 07:04 UTC, ifooth approved these changes

2023-06-14 07:04 UTC, merged