bcs-user-manager新增tracing
TencentBlueKing/bk-bcs pull request #2271
Opened 2023-06-07 09:02 UTC by LidolLxf

bcs-user-manager新增tracing

2023-06-08 12:14 UTC, ifooth commented on bcs-services/bcs-user-manager/app/pkg/cmanager/clustermanager/clustermanager.pb.go
新增这个文件的作用是？

2023-06-08 12:14 UTC, ifooth commented on bcs-services/bcs-user-manager/options/bcs_api.go
> +		err2 := resp.Body.Close()
直接defer resp.Body.Close() 就好

2023-06-08 12:14 UTC, ifooth commented on bcs-services/bcs-user-manager/options/bcs_api.go
> +	client := &http.Client{}
这里的client每次新建， tcp应该没有复用吧， 解决
- 提到一个结构体或者全局变量
- or 使用现成的库

2023-06-09 02:12 UTC, LidolLxf commented on bcs-services/bcs-user-manager/app/pkg/cmanager/clustermanager/clustermanager.pb.go
新增这个文件主要是调用clustermanager的结构体，requestBody和responseBody，确实是有多余的代码，如果不用clustermanager_pb的，那也需要建一个属于clustermanager调用的model

2023-06-14 03:46 UTC, adevjoe approved these changes

2023-06-14 03:58 UTC, adevjoe requested changes

2023-06-14 03:58 UTC, adevjoe commented on bcs-services/bcs-user-manager/app/tracing/config.go
> +func NewConfig(opts ...Option) *config {
代码规范：返回值不能是不可导出的结构体，`config` 需要改成 `Config`

2023-06-14 03:58 UTC, adevjoe commented on bcs-services/bcs-user-manager/app/tracing/config.go
> +	WriteEvents
导出变量需要注释

2023-06-14 07:02 UTC, ifooth approved these changes

2023-06-14 07:02 UTC, ifooth commented on bcs-services/bcs-user-manager/options/bcs_api.go
> +	req, err := http.NewRequest(method, url, bytes.NewReader(byteRequest))
没有超时，超时机制建议使用ctx, 可以在上层传入超时 context

2023-06-14 07:02 UTC, merged