minor: 修改完善apiserver-proxy设计部署文档
TencentBlueKing/bk-bcs pull request #2330
Opened 2023-07-05 06:51 UTC by Maclon9573

2023-07-05 08:03 UTC, abstractmj requested changes

2023-07-05 08:03 UTC, abstractmj commented on docs/features/bcs-apiserver-proxy/bcs-apiserver-proxy.md
> +        - 10.103.97.2/32
存在IP硬编码，建议改成一个虚拟的假地址

2023-07-05 08:18 UTC, Maclon9573 commented on docs/features/bcs-apiserver-proxy/bcs-apiserver-proxy.md
> +        - 10.103.97.2/32
已修改

2023-07-06 09:34 UTC, abstractmj approved these changes
LGTM

2023-07-06 09:38 UTC, abstractmj approved these changes
LGTM

2023-07-06 09:38 UTC, merged