集群部署工具框架设计 #2347
TencentBlueKing/bk-bcs pull request #2360
Opened 2023-07-21 01:50 UTC by ypxns

集群部署工具框架设计 # 增加安装nginx ingress逻辑

2023-07-21 01:51 UTC, tencentblueking-adm commented
[![CLA assistant check](https://bk-cla.bktencent.com:443/pull/badge/not_signed)](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-bcs?pullRequest=2360) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-bcs?pullRequest=2360) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bk-cla.bktencent.com:443/check/TencentBlueKing/bk-bcs?pullRequest=2360) it.</sub>

2023-08-02 06:07 UTC, bingoct commented on bcs-ops/k8s/install_nginx_ingress.sh
> +    helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
这个url 不要写死，用户可能拉不到

2023-08-02 06:09 UTC, bingoct commented on bcs-ops/k8s/install_nginx_ingress.sh
> +    check_dependency kubectl
顺便用kubectl检查下 集群的状态再执行。可参考

check_k8s_status() {
  if ! command -v kubectl &>/dev/null; then
    utils::log "FATAL" "can not find kubectl"
  fi

  if ! kubectl cluster-info 2>/dev/null; then
    utils::log "FATAL" "fail to get k8s cluster info"
  fi
  return 0
}

2023-08-02 06:15 UTC, bingoct requested changes
nginx-ingress-controller helm  chart 不要写死。
检测kubectl后顺便检查测下集群的状态

2023-08-02 08:10 UTC, bingoct approved these changes

2023-08-02 08:31 UTC, denglouping approved these changes

2023-08-03 12:53 UTC, abstractmj approved these changes

2023-08-03 12:53 UTC, merged