bcs-monitor新增PodMonitor
TencentBlueKing/bk-bcs pull request #2374
Opened 2023-07-26 03:18 UTC by LidolLxf

bcs-monitor新增PodMonitor

2023-07-28 02:18 UTC, adevjoe requested changes

2023-07-28 02:18 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/api/pod_monitor/pod_monitor.go
> +		return nil, nil
podMonitor := make([]*v1.PodMonitor, 0)

返回一个空数组，不要返回 nil，因为前端会报错

2023-07-28 02:18 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/api/pod_monitor/pod_monitor.go
> +// @Router  /pod_monitors/create/namespaces/:namespace/podmonitors/:name [post]
这里 route 应该没有 `:name`

2023-07-31 07:01 UTC, adevjoe approved these changes

2023-07-31 09:04 UTC, ifooth approved these changes

2023-07-31 09:04 UTC, merged