helm-manager 支持纳管命令行安装的 release
TencentBlueKing/bk-bcs pull request #2375
Opened 2023-07-26 06:58 UTC by Ambition9186

- helm-manager 支持纳管命令行安装的 release

2023-07-27 09:02 UTC, adevjoe requested changes

2023-07-27 09:02 UTC, adevjoe commented on bcs-services/bcs-helm-manager/proto/bcs-helm-manager/bcs-helm-manager.proto
> +    required string repoName = 5[(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {
都改成 optional

2023-07-27 09:02 UTC, adevjoe commented on bcs-services/bcs-helm-manager/proto/bcs-helm-manager/bcs-helm-manager.proto
> +    required string chartName = 6[(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {
同上

2023-07-27 09:02 UTC, adevjoe commented on bcs-services/bcs-helm-manager/proto/bcs-helm-manager/bcs-helm-manager.proto
> +    rpc RecordRelease(RecordReleaseReq) returns (RecordReleaseResp) {
方法名改为 `ImportClusterRelease` 吧，record 不太能表达接口的意思。

url 也改下，`/helmmanager/v1/projects/{projectCode}/clusters/{clusterID}/namespaces/{namespace}/releases/{name}/import`

2023-07-27 09:02 UTC, adevjoe commented on bcs-services/bcs-helm-manager/internal/actions/release/record.go
> +		return nil
这个方法统一返回 error，上一层 Handle 统一处理错误。根据 error 执行 `l.setResp()`

2023-07-27 09:02 UTC, adevjoe commented on bcs-services/bcs-helm-manager/internal/actions/release/record.go
> +		Status:       helmrelease.StatusPendingInstall.String(),
这里取 detail 里面的状态

2023-07-27 12:21 UTC, adevjoe requested changes

2023-07-27 12:21 UTC, adevjoe commented on bcs-services/bcs-helm-manager/proto/bcs-helm-manager/bcs-helm-manager.proto
> +            title : "RecordChartReleaseReq"
这里没改

2023-07-27 12:21 UTC, adevjoe commented on bcs-services/bcs-helm-manager/proto/bcs-helm-manager/bcs-helm-manager.proto
> +            title : "GetChartReleaseResp"
这里的 title 和 description 没改

2023-07-27 12:21 UTC, adevjoe commented on bcs-services/bcs-helm-manager/internal/actions/release/import.go
> +	if err != nil && !errors.Is(err, driver.ErrReleaseNotFound) {
release not found 错误也要抛出来

2023-07-31 07:00 UTC, adevjoe approved these changes

2023-07-31 09:05 UTC, ifooth approved these changes

2023-08-01 06:56 UTC, merged