封装一个i1n8的公共包
TencentBlueKing/bk-bcs pull request #2422
Opened 2023-08-09 09:14 UTC by Ambition9186

- 封装一个i1n8的公共包，通过go embed 加载对应模块的翻译文件
- 提供外部翻译函数，翻译模板、模板变量
- 编写使用文档和测试用例

2023-08-10 02:01 UTC, adevjoe requested changes

2023-08-10 02:01 UTC, adevjoe commented on bcs-common/pkg/i18n/i18n/testdata/assets.go
这里是不是多了一个 i18n 文件夹

2023-08-10 02:01 UTC, adevjoe commented on bcs-common/pkg/i18n/README.MD
> +
目录结构也给个示例哈

2023-08-10 02:01 UTC, adevjoe commented on bcs-common/pkg/i18n/README.MD
> +# I18N国际化-使用介绍
i18n 应该是小写

2023-08-10 02:01 UTC, adevjoe commented on bcs-common/pkg/i18n/ctx.go
> +func LanguageFromCtx(ctx context.Context) string {
还需要一个给 `context` 注入语言类型的方法，比如在中间件使用。

2023-08-14 01:43 UTC, adevjoe approved these changes

2023-08-14 08:24 UTC, ifooth approved these changes

2023-08-14 08:24 UTC, merged