cluster-resource pod下容器列表新增initContainer
TencentBlueKing/bk-bcs pull request #2438
Opened 2023-08-16 06:13 UTC by LidolLxf

cluster-resource pod下容器列表新增initContainer

2023-08-17 07:24 UTC, adevjoe requested changes

2023-08-17 07:24 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/action/resp/resp.go
> +	for _, initContainerStatus := range mapx.GetList(podManifest, "status.initContainerStatuses") {
这里和上面 container 循环有重复代码，可以优化下

2023-08-17 09:02 UTC, adevjoe requested changes

2023-08-17 09:02 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/action/resp/resp.go
> +	*containers = append(*containers, map[string]interface{}{
这样写看起来怪怪的，弄成返回值更好吧

2023-08-17 09:16 UTC, adevjoe approved these changes

2023-08-21 02:28 UTC, ifooth approved these changes

2023-08-21 02:28 UTC, merged