feature: support netservice controller
TencentBlueKing/bk-bcs pull request #2440
Opened 2023-08-16 09:42 UTC by Maclon9573

[Underlay -- Macvlan网络方案开发#2410](https://github.com/TencentBlueKing/bk-bcs/issues/2410)

2023-08-22 07:36 UTC, abstractmj requested changes

2023-08-22 07:36 UTC, abstractmj commented on bcs-runtime/bcs-k8s/bcs-component/bcs-netservice-controller/controllers/bcsnetipclaim_controller.go
> +		if claim.Status.Phase == constant.BCSNetIPClaimBoundedStatus {
why netipclaim cannot be deleted when in Bounded Status?
What should I do if I need to delete it

2023-08-22 07:36 UTC, abstractmj commented on bcs-runtime/bcs-k8s/bcs-component/bcs-netservice-controller/controllers/bcsnetpool_controller.go
> +func (r *BCSNetPoolReconciler) syncReservedBCSNetIP(ctx context.Context, netPool *netservicev1.BCSNetPool) {
need error handling

2023-08-22 07:36 UTC, abstractmj commented on bcs-runtime/bcs-k8s/bcs-component/bcs-netservice-controller/controllers/bcsnetpool_controller.go
> +	r.syncReservedBCSNetIP(ctx, netPool)
need error handling

2023-08-22 07:36 UTC, abstractmj commented on bcs-runtime/bcs-k8s/bcs-component/bcs-netservice-controller/controllers/bcsnetpool_controller.go
> +		for _, ip := range netPool.Spec.AvailableIPs {
Here you need to list ip object from the cluster, not from the field of pool spec, because it is possible that the user has reduced the ip list in the previous operation, but failed

2023-08-22 08:16 UTC, Maclon9573 commented on bcs-runtime/bcs-k8s/bcs-component/bcs-netservice-controller/controllers/bcsnetipclaim_controller.go
> +		if claim.Status.Phase == constant.BCSNetIPClaimBoundedStatus {
Fixed. Now, allow user to delete Claim when bounded IP is not in active state.

2023-08-22 08:16 UTC, Maclon9573 commented on bcs-runtime/bcs-k8s/bcs-component/bcs-netservice-controller/controllers/bcsnetpool_controller.go
> +func (r *BCSNetPoolReconciler) syncReservedBCSNetIP(ctx context.Context, netPool *netservicev1.BCSNetPool) {
Fixed.

2023-08-22 08:16 UTC, Maclon9573 commented on bcs-runtime/bcs-k8s/bcs-component/bcs-netservice-controller/controllers/bcsnetpool_controller.go
> +	r.syncReservedBCSNetIP(ctx, netPool)
Fixed.

2023-08-22 08:17 UTC, Maclon9573 commented on bcs-runtime/bcs-k8s/bcs-component/bcs-netservice-controller/controllers/bcsnetpool_controller.go
> +		for _, ip := range netPool.Spec.AvailableIPs {
Fixed.

2023-08-24 07:44 UTC, abstractmj requested changes

2023-08-24 07:44 UTC, abstractmj commented on bcs-runtime/bcs-k8s/bcs-component/bcs-netservice-controller/internal/httpsvr/handler.go
> +//				return ip, nil
remove dead code

2023-08-24 07:44 UTC, abstractmj commented on bcs-runtime/bcs-k8s/bcs-component/bcs-netservice-controller/internal/httpsvr/handler.go
> +		message := fmt.Sprintf("update IP [%s] status failed", netIPReq.IPAddr)
print err message

2023-08-24 10:50 UTC, abstractmj requested changes

2023-08-24 10:50 UTC, abstractmj commented on bcs-runtime/bcs-k8s/bcs-component/bcs-netservice-controller/main.go
> +	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
import orders

2023-08-24 11:28 UTC, abstractmj approved these changes

2023-08-24 11:28 UTC, merged