feature: add ip scheduler v3 for k8s-custom-scheduler
TencentBlueKing/bk-bcs pull request #2478
Opened 2023-08-23 11:49 UTC by Maclon9573

2023-08-25 09:53 UTC, abstractmj requested changes

2023-08-25 09:53 UTC, abstractmj commented on bcs-runtime/bcs-k8s/bcs-component/bcs-k8s-custom-scheduler/pkg/ipscheduler/v3/ipscheduler.go
> +		if err := getBCSNetCRD(extenderArgs.Pod.Namespace, fixedIpAnnotationKey, "bcsnetipclaims", resource); err != nil {
此处叫CRD不合适，改成CR

2023-08-25 09:53 UTC, abstractmj commented on bcs-runtime/bcs-k8s/bcs-component/bcs-k8s-custom-scheduler/pkg/ipscheduler/v3/ipscheduler.go
> +	blog.Infof("%v", canNotSchedule)
此处日志打印信息不全

2023-08-25 10:32 UTC, Maclon9573 commented on bcs-runtime/bcs-k8s/bcs-component/bcs-k8s-custom-scheduler/pkg/ipscheduler/v3/ipscheduler.go
> +	blog.Infof("%v", canNotSchedule)
Fixed

2023-08-28 02:41 UTC, abstractmj approved these changes

2023-08-28 02:41 UTC, merged