bcs-helm-manager addons 配置支持动态加载、组件库添加组件列表接口
TencentBlueKing/bk-bcs pull request #2538
Opened 2023-09-07 08:42 UTC by LidolLxf

bcs-helm-manager addons 配置支持动态加载、组件库添加组件列表接口

2023-09-12 06:46 UTC, adevjoe requested changes

2023-09-12 06:46 UTC, adevjoe commented on bcs-services/bcs-helm-manager/internal/actions/addons/list.go
> +		version, err := l.getLatestVersion(ctx, value.ChartName)
这里不用从 bkrepo 获取最新版本，如果数据库中没有则显示为空

2023-09-12 06:46 UTC, adevjoe commented on bcs-services/bcs-helm-manager/internal/actions/addons/list.go
> +		if version == "" {
不需要这个逻辑

2023-09-13 03:45 UTC, adevjoe approved these changes

2023-09-13 03:51 UTC, ifooth approved these changes

2023-09-13 03:51 UTC, merged