cluster-resources add audit sdk
TencentBlueKing/bk-bcs pull request #2550
Opened 2023-09-12 06:33 UTC by Ambition9186

- cluster-resources add audit sdk

2023-09-19 08:06 UTC, adevjoe requested changes

2023-09-19 08:06 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/config/config.go
> +type ReleaseConfig struct {
不需要单独配置，使用 `BCSAPIGW ` 中的配置即可

2023-09-19 08:06 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/wrapper/response.go
> +	ProjectID     string   `json:"projectID" yaml:"projectID"`
保留以下字段：
```
ProjectID
ClusterID
ProjectCode
Namespace
Name
Kind
Version
```

2023-09-21 02:35 UTC, adevjoe approved these changes

2023-09-21 02:43 UTC, ifooth approved these changes

2023-09-21 03:37 UTC, merged