bcs-monitor&bcs-project-manager操作记录SDK接入
TencentBlueKing/bk-bcs pull request #2563
Opened 2023-09-14 09:31 UTC by LidolLxf

bcs-monitor&bcs-project-manager操作记录SDK接入

2023-09-19 07:42 UTC, adevjoe requested changes

2023-09-19 07:42 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/rest/rest.go
> +	FromRule  string `json:"from_rule" yaml:"from_rule"`
`FromRule ` 字段不需要

2023-09-19 07:42 UTC, adevjoe commented on bcs-services/bcs-project-manager/internal/wrapper/response.go
> +		}, audit.Action{ActionID: "create_project", ActivityType: audit.ActivityTypeCreate}
改成 `project_create`

2023-09-19 07:42 UTC, adevjoe commented on bcs-services/bcs-project-manager/internal/wrapper/response.go
> +	Key         string `json:"key" yaml:"key"`
`Key` 不需要

2023-09-19 07:42 UTC, adevjoe commented on bcs-services/bcs-project-manager/internal/wrapper/response.go
> +		}, audit.Action{ActionID: "update_project", ActivityType: audit.ActivityTypeUpdate}
改成 `project_edit`

2023-09-19 07:42 UTC, adevjoe commented on bcs-services/bcs-project-manager/internal/wrapper/response.go
> +		}, audit.Action{ActionID: "create_namespace", ActivityType: audit.ActivityTypeCreate}
改成 `namespace_create`

2023-09-19 07:42 UTC, adevjoe commented on bcs-services/bcs-project-manager/internal/wrapper/response.go
> +		}, audit.Action{ActionID: "update_namespace", ActivityType: audit.ActivityTypeUpdate}
改成 `namespace_update`

2023-09-19 07:42 UTC, adevjoe commented on bcs-services/bcs-project-manager/internal/wrapper/response.go
> +		}, audit.Action{ActionID: "delete_namespace", ActivityType: audit.ActivityTypeDelete}
改成 `namespace_delete`

2023-09-19 07:42 UTC, adevjoe commented on bcs-services/bcs-project-manager/internal/wrapper/response.go
> +	"Namespace.SyncNamespace": func(req server.Request, rsp interface{}) (audit.Resource, audit.Action) {
`SyncNamespace ` 不需要

2023-09-19 07:42 UTC, adevjoe commented on bcs-services/bcs-project-manager/internal/wrapper/response.go
> +	"Namespace.WithdrawNamespace": func(req server.Request, rsp interface{}) (audit.Resource, audit.Action) {
`WithdrawNamespace ` 不需要

2023-09-21 02:26 UTC, adevjoe approved these changes

2023-09-21 02:42 UTC, ifooth approved these changes

2023-09-21 02:42 UTC, merged