cluster-manager add audit sdk
TencentBlueKing/bk-bcs pull request #2571
Opened 2023-09-15 06:33 UTC by Ambition9186

- cluster-manager add audit sdk

2023-09-19 08:01 UTC, adevjoe requested changes

2023-09-19 08:01 UTC, adevjoe commented on bcs-services/bcs-cluster-manager/internal/options/options.go
> +	Release            ReleaseConfig         `json:"release" yaml:"release"`
不需要单独加一个配置，可以用 `ComponentDeploy ` 里面的 host 和 token

2023-09-19 08:01 UTC, adevjoe commented on bcs-services/bcs-cluster-manager/internal/utils/wrap.go
> +	Nodes          any      `json:"nodes" yaml:"nodes"`
`Nodes` `InnerIPs ` `NodeIPs ` 先不加了

2023-09-19 08:01 UTC, adevjoe commented on bcs-services/bcs-cluster-manager/internal/utils/wrap.go
> +		}, audit.Action{ActionID: "create_cluster", ActivityType: audit.ActivityTypeCreate}
改成 `cluster_create`

2023-09-19 08:01 UTC, adevjoe commented on bcs-services/bcs-cluster-manager/internal/utils/wrap.go
> +		}, audit.Action{ActionID: "import_cluster", ActivityType: audit.ActivityTypeCreate}
改成 `cluster_create`

2023-09-19 08:01 UTC, adevjoe commented on bcs-services/bcs-cluster-manager/internal/utils/wrap.go
> +		}, audit.Action{ActionID: "update_cluster", ActivityType: audit.ActivityTypeUpdate}
改成 `cluster_manage`

2023-09-19 08:01 UTC, adevjoe commented on bcs-services/bcs-cluster-manager/internal/utils/wrap.go
> +		}, audit.Action{ActionID: "delete_cluster", ActivityType: audit.ActivityTypeDelete}
改成 `cluster_delete`

2023-09-19 08:01 UTC, adevjoe commented on bcs-services/bcs-cluster-manager/internal/utils/wrap.go
> +		}, audit.Action{ActionID: "create_cloud_account", ActivityType: audit.ActivityTypeCreate}
改成 `cloud_account_create`

2023-09-19 08:01 UTC, adevjoe commented on bcs-services/bcs-cluster-manager/internal/utils/wrap.go
> +		}, audit.Action{ActionID: "update_cloud_account", ActivityType: audit.ActivityTypeUpdate}
改成 `cloud_account_manage`

2023-09-19 08:01 UTC, adevjoe commented on bcs-services/bcs-cluster-manager/internal/utils/wrap.go
> +		}, audit.Action{ActionID: "delete_cloud_account", ActivityType: audit.ActivityTypeDelete}
改成 `cloud_account_manage`

2023-12-01 06:42 UTC, evanlixin approved these changes
LGTM

2024-06-03 06:41 UTC, closed without merging