bcs-monitor规范修改golangci-lint
TencentBlueKing/bk-bcs pull request #2623
Opened 2023-09-21 10:00 UTC by LidolLxf

bcs-monitor规范修改golangci-lint

2023-09-21 12:20 UTC, ifooth commented on bcs-services/bcs-monitor/pkg/api/logrule/helper.go
> +// Package logrule ...
package 一个就可以了

2023-09-21 12:20 UTC, ifooth commented on bcs-services/bcs-monitor/pkg/query/query.go
> +func NewQueryAPI(ctx context.Context, reg *prometheus.Registry, tracer opentracing.Tracer, kitLogger gokit.Logger,
这里的写法也会有问题么~，具体规范是哪个

2023-09-21 12:20 UTC, ifooth commented on bcs-services/bcs-monitor/pkg/storegw/bcs_system/source/compute/container.go
> +	CLUSTERID = `cluster_id="%<clusterID>s", namespace="%<namespace>s", ` +
1. 命名可以改为ContainerMatcher
2. 公共的matcher可以base目录

2023-09-21 12:20 UTC, ifooth commented on bcs-services/bcs-monitor/pkg/storegw/bcs_system/source/bk_monitor/cluster.go
> +	SUMMAX = `sum(max by(bk_instance) (rate(node_disk_io_time_seconds_total{%<cluster>s, ` +
特定的，用小写非导出就好

2023-09-21 12:20 UTC, ifooth commented on bcs-services/bcs-monitor/pkg/storegw/bcs_system/source/bk_monitor/cluster.go
> +	SUMNODEFILE = `sum(node_filesystem_size_bytes{`
这个是解什么问题？ 重复率么？ 不多就nolint下， 这样非常不好看原生语法， 上面的如果不多，都可以nolint下

2023-09-22 02:06 UTC, LidolLxf commented on bcs-services/bcs-monitor/pkg/query/query.go
> +func NewQueryAPI(ctx context.Context, reg *prometheus.Registry, tracer opentracing.Tracer, kitLogger gokit.Logger,
函数体过长了，超过90行

2023-09-28 08:59 UTC, adevjoe requested changes

2023-09-28 08:59 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/api/metrics/container.go
> +		`bcs:container:cpu_usage{` + CLUSTERID + `}`
这种不用处理

2023-09-28 08:59 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/api/metrics/container.go
> +		`bcs:container:cpu_usage{` + CLUSTERID + `}`
其他类似的也是

2023-10-07 03:36 UTC, adevjoe approved these changes

2023-10-07 11:58 UTC, wenxinlee2015 approved these changes

2023-10-07 11:59 UTC, merged