Add: Webconsole audit sdk
TencentBlueKing/bk-bcs pull request #2625
Opened 2023-09-21 12:35 UTC by jonesyang12

2023-09-21 12:49 UTC, adevjoe requested changes

2023-09-21 12:49 UTC, adevjoe commented on bcs-services/bcs-webconsole/route/audit.go
> +				ResourceID: res.ProjectID, ResourceData: res.toMap()},
这里资源 ID 用 clusterID 吧

2023-09-21 12:49 UTC, adevjoe commented on bcs-services/bcs-webconsole/route/audit.go
> +	RequestID   string `json:"request_id" yaml:"request_id"`
这里不需要记录 RequestID，其他地方已经记录了

2023-09-21 12:49 UTC, adevjoe commented on bcs-services/bcs-webconsole/route/audit.go
> +	result.ResultCode = data.Code
这里要记录失败的情况

2023-09-22 03:15 UTC, adevjoe approved these changes

2023-09-25 09:35 UTC, wenxinlee2015 approved these changes

2023-09-25 09:35 UTC, merged