代码规范：storage lint
TencentBlueKing/bk-bcs pull request #2650
Opened 2023-09-27 08:48 UTC by jonesyang12

2023-09-27 09:47 UTC, adevjoe requested changes

2023-09-27 09:47 UTC, adevjoe commented on bcs-services/bcs-storage/pkg/server/server.go
> +		grpcDialOpts = append(grpcDialOpts, grpc.WithTransportCredentials(insecure.NewCredentials()))
不做修改

2023-09-27 09:47 UTC, adevjoe commented on bcs-services/bcs-storage/storage/actions/lib/store.go
> -var (
不做修改

2023-09-27 09:47 UTC, adevjoe commented on bcs-services/bcs-storage/storage/actions/v1http/dynamic/queue_operate.go
> +		err := publishDynamicResourceToQueue(data, featTags, msgqueue.EventTypeUpdate)
不做修改

2023-09-27 09:47 UTC, adevjoe commented on bcs-services/bcs-storage/storage/watchbus/dispatcher.go
> +		for event := range listenerCh {
不做修改

2023-09-28 07:49 UTC, jonesyang12 commented on bcs-services/bcs-storage/storage/actions/v1http/dynamic/queue_operate.go
> +		err := publishDynamicResourceToQueue(data, featTags, msgqueue.EventTypeUpdate)
这里的入参就是nsFeatTags，我们用了featTags参数名其实就是用的nsFeatTags

2023-09-28 08:17 UTC, adevjoe approved these changes

2023-09-28 09:41 UTC, wenxinlee2015 approved these changes

2023-09-28 09:41 UTC, merged