代码规范：netservice lint
TencentBlueKing/bk-bcs pull request #2651
Opened 2023-09-27 08:49 UTC by jonesyang12

2023-09-27 09:36 UTC, adevjoe requested changes

2023-09-27 09:36 UTC, adevjoe commented on bcs-services/bcs-netservice/storage/zookeeper/zookeeper.go
> -		for {
这里不要修改

2023-09-28 08:15 UTC, adevjoe approved these changes

2023-09-28 09:41 UTC, wenxinlee2015 approved these changes

2023-09-28 09:41 UTC, merged