feature: gameworkload rollout
TencentBlueKing/bk-bcs pull request #2697
Opened 2023-10-20 04:00 UTC by jonesyang12

gameworkload rollout history/restart/undo

2023-10-20 07:03 UTC, adevjoe requested changes

2023-10-20 07:03 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/action/resource/resource.go
> +	if m.GroupVersion == "tkex.tencent.com/v1alpha1" {
只要区分 patchType 就可以了，不需要单独 return

2023-10-20 07:17 UTC, adevjoe approved these changes

2023-10-23 02:04 UTC, ifooth approved these changes

2023-10-23 02:04 UTC, merged