审计清理及资源视图列表增加字段识别
TencentBlueKing/bk-bcs pull request #2787
Opened 2023-11-29 06:37 UTC by LidolLxf

审计清理及资源视图列表增加字段识别

2023-11-29 08:38 UTC, adevjoe requested changes

2023-11-29 08:38 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/resource/formatter/workload.go
> +	ret["isByHelm"] = parseLabelsHelm(manifest)
统一放到 `CommonFormatRes(manifest)` 里，ret key 改成 `immutable`

2023-11-29 08:38 UTC, adevjoe commented on bcs-services/bcs-user-manager/options/options.go
> +	Days         int      `json:"days" yaml:"days"`
这里用 `duration`，使用 `time.ParseDuration("3d")` 解析更清晰。

2023-11-29 08:38 UTC, adevjoe commented on bcs-services/bcs-user-manager/options/options.go
> +// AuditClean 审查清理
都改成操作记录清理，`activity`

2023-11-29 08:38 UTC, adevjoe commented on bcs-services/bcs-user-manager/app/user-manager/user-manager.go
> +	if err := g.Wait(); err != nil {
这里阻塞了，直接 `go sqlstore.IntervalDeleteActivity(ctx)` 就可以

2023-11-29 08:38 UTC, adevjoe commented on bcs-services/bcs-user-manager/app/user-manager/storages/sqlstore/activity.go
> +func IntervalDeleteActivity(ctx context.Context) error {
定时任务逻辑放到 `app/user-manager/job` 里面，清理数据库的 sql 可以放到当前目录，类似于 `CreateActivity`

2023-11-29 08:41 UTC, adevjoe requested changes

2023-11-29 08:41 UTC, adevjoe commented on bcs-services/bcs-user-manager/app/user-manager/storages/sqlstore/activity.go
> +	err := GCoreDB.Where("resource_type in (?) and created_at < ?",
分批删除

2023-11-29 08:41 UTC, adevjoe commented on bcs-services/bcs-user-manager/app/user-manager/storages/sqlstore/activity.go
> +	timer := time.NewTicker(time.Second * 5)
5s 检查一次太频繁了，设置个参数吧，默认 1d

2023-11-30 02:58 UTC, adevjoe requested changes

2023-11-30 02:58 UTC, adevjoe commented on bcs-services/bcs-user-manager/app/user-manager/storages/sqlstore/activity.go
> +func BatchDeleteActivity() error {
把逻辑从 store 迁出去，store 仅进行数据库操作

2023-11-30 02:58 UTC, adevjoe commented on bcs-services/bcs-user-manager/app/user-manager/job/activity/activity.go
> +				return err
这里不用退出，不然数据库出错一次，整个任务就退出了

2023-12-01 02:35 UTC, adevjoe approved these changes

2023-12-01 02:57 UTC, ifooth approved these changes

2023-12-01 02:57 UTC, merged