feat:新增模板文件相关接口
TencentBlueKing/bk-bcs pull request #2836
Opened 2023-12-15 08:26 UTC by LidolLxf

feat:新增模板文件相关接口

2023-12-28 03:48 UTC, adevjoe requested changes

2023-12-28 03:48 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +      delete: "/clusterresources/v1/projects/{projectCode}/template/space/{id}/{isRelateDelete}"
isRelateDelete 放到 query 里

2023-12-28 03:48 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +      post: "/clusterresources/v1/projects/{projectCode}/template/version"
`/clusterresources/v1/projects/{projectCode}/templates/versions`
同下

2023-12-29 01:40 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/action/constants.go
> +
这里使用英文

2023-12-29 07:18 UTC, adevjoe requested changes

2023-12-29 07:18 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources_grpc.pb.go
这个应该没有吧，用 make proto 生成应该没这个

2023-12-29 09:54 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +	string name = 2 [(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {
projectCode 都是 32 位

2023-12-29 09:58 UTC, adevjoe requested changes
1

2024-01-02 02:48 UTC, adevjoe requested changes

2024-01-02 02:48 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +			put: "/clusterresources/v1/projects/{projectCode}/template/spaces"
id 放在路径里面

2024-01-02 02:48 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +			put: "/clusterresources/v1/projects/{projectCode}/template/metadatas"
id 放到路径里面

2024-01-02 02:48 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +			put: "/clusterresources/v1/projects/{projectCode}/template/versions"
id 放在路径里

2024-01-02 02:48 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +	string creator = 6 [(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {
creator 不能更新

2024-01-02 02:48 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +	string content = 5 [(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {
内容不限制大小

2024-01-02 02:48 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +	string version = 4 [(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {
描述不限制大小

2024-01-02 02:48 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +	string creator = 6 [(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {
creator 不更新

2024-01-02 02:48 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +	string content = 4 [(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {
不限制大小

2024-01-02 02:48 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +	string description = 2 [(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {
32

2024-01-02 02:48 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +	string resourceType = 5 [(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {
描述不限制大小

2024-01-02 02:48 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +	}, (validate.rules).string = {min_len : 1, max_len : 64}];
更新者不更新

2024-01-02 02:48 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +	repeated string tags = 7 [(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {
tags 可以为空

2024-01-02 02:48 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +	}, (validate.rules).string = {min_len : 1, max_len : 64}];
版本模式使用枚举

2024-01-02 02:48 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +}
不限制大小

2024-01-02 02:48 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +	string version = 10 [(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {
描述不限制大小

2024-01-02 02:48 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +	}, (validate.rules).repeated = {min_items : 1}];
可以为空

2024-01-02 02:48 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +	}, (validate.rules).string = {min_len : 1, max_len : 64}];
不更新

2024-01-02 02:48 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +	}, (validate.rules).string = {min_len : 1, max_len : 64}];
不更新

2024-01-02 02:48 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +	string templateSpace = 4 [(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {
不限制大小

2024-01-02 12:04 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/store/entity/templateversion.go
> +	UpdateAt      int64              `json:"updateAt" bson:"updateAt"`
这里只需要 `CreateAt`

2024-01-02 12:08 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +	rpc UpdateTemplateVersion(UpdateTemplateVersionReq) returns (CommonResp) {
不需要更新版本，只能创建版本

2024-01-02 12:16 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +	}, (validate.rules).string = {min_len : 1, max_len : 64}];
创建模板文件版本添加一个校验，版本已存在则报‘版本已存在’，另外添加一个字段标识是否可以覆盖版本。

2024-01-02 12:23 UTC, adevjoe requested changes

2024-01-02 12:23 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/store/entity/templateversion.go
> +	UpdateAt      int64              `json:"updateAt" bson:"updateAt"`
这里只需要 `CreateAt`

2024-01-02 12:23 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +	rpc UpdateTemplateVersion(UpdateTemplateVersionReq) returns (CommonResp) {
不需要更新版本，只能创建版本

2024-01-02 12:23 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +message CreateTemplateVersionReq {
创建模板文件版本添加一个校验，版本已存在则报‘版本已存在’，另外添加一个字段标识是否可以覆盖版本。

2024-01-03 03:52 UTC, adevjoe requested changes

2024-01-03 03:52 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +	bool isCover = 7 [(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {
改成 `force` 吧

2024-01-03 07:18 UTC, adevjoe approved these changes

2024-01-03 07:47 UTC, ifooth approved these changes

2024-01-03 07:47 UTC, merged