feat：新增环境管理相关接口
TencentBlueKing/bk-bcs pull request #2882
Opened 2023-12-28 03:31 UTC by LidolLxf

feat：新增环境管理相关接口

2024-01-02 12:37 UTC, adevjoe requested changes

2024-01-02 12:37 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources_grpc.pb.go
重新 `make proto` 生成下

2024-01-02 12:37 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +			get: "/clusterresources/v1/projects/{projectCode}/env/manages/{id}"
不需要添加 `/manages`

2024-01-02 12:37 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +	}, (validate.rules).string = {min_len : 1, max_len : 64}];
更新也能更新名称

2024-01-02 12:37 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +	repeated Associate associates = 3 [(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {
这里叫 clusterdNamespaces

2024-01-02 12:37 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +	string namespace = 2 [(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {
命名空间支持多个

2024-01-03 08:51 UTC, adevjoe approved these changes

2024-01-03 09:06 UTC, ifooth approved these changes

2024-01-03 09:06 UTC, merged