feat：新增模板集相关metrics
TencentBlueKing/bk-bcs pull request #2890
Opened 2024-01-09 03:20 UTC by LidolLxf

feat：新增模板集相关metrics

2024-01-16 07:30 UTC, adevjoe requested changes

2024-01-16 07:30 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/metrics/metrics.go
> +func RecordTemplateMetrics(method string, code int32, started time.Time) {
都应该都记录，不只记录模板集

2024-01-18 12:22 UTC, adevjoe requested changes

2024-01-18 12:22 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/wrapper/response.go
> +				metrics.RecordMetrics(req.Method(), r.Code, startTime)
这个和上面没有不一样，可以一起记录吧

2024-01-19 09:25 UTC, ifooth approved these changes

2024-01-19 09:25 UTC, merged