feat：Helm Release 详情扩展
TencentBlueKing/bk-bcs pull request #2891
Opened 2024-01-10 09:10 UTC by LidolLxf

feat：Helm Release 详情扩展

2024-01-16 07:28 UTC, adevjoe requested changes

2024-01-16 07:28 UTC, adevjoe commented on bcs-services/bcs-helm-manager/internal/handler/release.go
> +func (hm *HelmManager) GetReleaseDetailExtend(
没有加上鉴权，应该调用不通的，可以先测试下

2024-01-18 12:23 UTC, adevjoe approved these changes

2024-01-19 09:25 UTC, ifooth approved these changes

2024-01-19 09:25 UTC, merged