feat：helmctl 添加上传 chat 的命会
TencentBlueKing/bk-bcs pull request #2906
Opened 2024-01-18 09:40 UTC by LidolLxf

feat：helmctl 添加上传 chat 的命会

2024-01-24 03:09 UTC, adevjoe commented
> feat：helmctl 添加上传 chat 的命会

标题和正文的 chart 打错了

2024-01-24 03:20 UTC, adevjoe requested changes

2024-01-24 03:20 UTC, adevjoe commented on bcs-services/bcs-helm-manager/internal/client/cmd/push.go
> +		Example: "helmctl push <file_or_dir> -p <project_code> -r <repo_name> -V <version> -f",
版本用小写 `-v` 吧，统一下

2024-01-24 03:20 UTC, adevjoe commented on bcs-services/bcs-helm-manager/internal/client/pkg/client/chart.go
> +func (ct *chart) Create(ctx context.Context, req *utilschart.UploadChart) error {
方法名改成 UploadChart 或者是 PushChart

2024-01-30 03:57 UTC, adevjoe approved these changes

2024-01-30 06:44 UTC, ifooth approved these changes

2024-01-30 06:44 UTC, merged