fix：适配于bcs-monitor旧日志的打印方式
TencentBlueKing/bk-bcs pull request #3035
Opened 2024-03-12 03:47 UTC by LidolLxf

fix：适配于bcs-monitor旧日志的打印方式

2024-03-12 03:53 UTC, LidolLxf commented
![微信图片_20240312114523](https://github.com/TencentBlueKing/bk-bcs/assets/130628034/face9a94-0b33-4ae3-bfc7-ae3dcb0b5d5b)
蓝色：bkmonitor-kits/logger，红色：blog

2024-03-13 08:05 UTC, adevjoe requested changes
pr 名字改下，比如：blog 支持输出键值对日志

2024-03-13 08:05 UTC, adevjoe commented on bcs-common/common/blog/blog.go
> +	// Infow 适配于bcs-monitor的Infow 键值对打印
不用单独写适配 bcs-monitor，写支持 key-values 输出就可以了

2024-03-13 08:05 UTC, adevjoe commented on bcs-common/common/blog/glog/glog.go
> +	Infow Levelw = iota
加个注释

2024-03-15 02:51 UTC, ifooth approved these changes

2024-03-15 02:52 UTC, merged