feat：bcs-helm-manager release 列表接口进一步优化
TencentBlueKing/bk-bcs pull request #3063
Opened 2024-03-20 09:40 UTC by LidolLxf

feat：bcs-helm-manager release 列表接口进一步优化

2024-04-01 04:05 UTC, adevjoe requested changes

2024-04-01 04:05 UTC, adevjoe commented on bcs-services/bcs-helm-manager/internal/release/bcs/list.go
> +func getVersion(s string) int {
改成 `parseVersion`

2024-04-01 04:05 UTC, adevjoe commented on bcs-services/bcs-helm-manager/internal/release/bcs/list.go
> +func getTime(s string) time.Time {
改成 `parseStringUnixTime`

2024-04-01 04:05 UTC, adevjoe commented on bcs-services/bcs-helm-manager/internal/release/bcs/list.go
> +	req, err := http.NewRequestWithContext(ctx, "GET", url, nil)
http client 使用类似 bcs-monitor 里面的 http client，有封装好的，可以移植过来

2024-04-01 04:05 UTC, adevjoe commented on bcs-services/bcs-helm-manager/internal/release/bcs/list.go
>  func (c *cluster) list(ctx context.Context, option release.ListOption) (int, []*release.Release, error) {
可以新增一个 grpc 接口，和以前的 release list 接口区分开来，因为前端还没有改，先做兼容

2024-04-17 03:35 UTC, adevjoe requested changes

2024-04-17 03:35 UTC, adevjoe commented on bcs-services/bcs-helm-manager/internal/actions/release/listv2.go
> +func (l *ListReleaseV2Action) list() (*helmmanager.ReleaseListData, error) {
只是拉取集群里的 release 不同，看其他的能不能复用

2024-05-07 02:03 UTC, adevjoe requested changes

2024-05-07 02:03 UTC, adevjoe commented on bcs-services/bcs-helm-manager/internal/store/entity/secret.go
> +type SecretList struct {
secret 可以引用 k8s 的库，不用 copy 一份放这里

2024-05-31 07:20 UTC, adevjoe approved these changes

2024-05-31 07:24 UTC, ifooth approved these changes

2024-05-31 07:24 UTC, merged