feat：bcs-ui 新增前端埋点接口
TencentBlueKing/bk-bcs pull request #3072
Opened 2024-03-26 08:14 UTC by LidolLxf

feat：bcs-ui 新增前端埋点接口

2024-04-01 06:34 UTC, adevjoe requested changes

2024-04-01 06:34 UTC, adevjoe commented on bcs-ui/pkg/web/web.go
> +	r.With(metrics.RequestCollect("DataPrintHandler")).Post("/data_print", DataPrintHandler)
改成 `/report` 把

2024-04-09 03:59 UTC, adevjoe approved these changes

2024-04-09 04:11 UTC, ifooth commented on bcs-ui/pkg/web/web.go
> +	fmt.Println(stringBuffer.String())
正式不要打印

2024-04-10 06:49 UTC, ifooth approved these changes

2024-04-10 06:49 UTC, merged