feat：资源列表只展示基本字段，manifest 按需过滤
TencentBlueKing/bk-bcs pull request #3154
Opened 2024-04-25 10:31 UTC by LidolLxf

feat：资源列表只展示基本字段，manifest 按需过滤

2024-04-30 06:50 UTC, adevjoe requested changes

2024-04-30 06:50 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/resource/formatter/constants.go
> +	resCsts.SA:     PruneConfig,
这些还是单独封装一下吧，不要都用 `PruneConfig `

2024-05-07 02:04 UTC, adevjoe approved these changes

2024-05-07 07:44 UTC, ifooth approved these changes

2024-05-07 07:44 UTC, merged