feat：bcs-monitor 支持 cluster-manager节点池数目趋势图 api
TencentBlueKing/bk-bcs pull request #3181
Opened 2024-05-09 10:27 UTC by LidolLxf

feat：bcs-monitor 支持 cluster-manager节点池数目趋势图 api

2024-05-13 12:43 UTC, adevjoe requested changes

2024-05-13 12:43 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/api/routes.go
> +		route.GET("/group/:group/node_num", rest.RestHandlerFunc(metrics.ClusterGroupNodeNum))
这里节点池统一命名 `nodegroup` `Nodegroup` 吧

2024-05-13 12:43 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/storegw/bcs_system/source/bk_monitor/group.go
> +		"clusterID": clusterID,
这里 `clusterID` 要通过配置文件传过来，因为 `bkbcs_clustermanager_cluster_group_maxNodeNum ` metrics 只在bcs 自己所在集群存在，如果查其他集群的节点池 metrics，也要通过 bcs 所在集群去查。

2024-05-15 03:48 UTC, adevjoe requested changes

2024-05-15 03:48 UTC, adevjoe commented on bcs-services/bcs-monitor/pkg/api/metrics/group.go
> +		"clusterId": c.ClusterId,
这里没改

2024-05-21 02:51 UTC, adevjoe approved these changes

2024-05-21 02:59 UTC, ifooth approved these changes

2024-05-21 02:59 UTC, merged