feat:配置示例需求部分代码 --story=885066745
TencentBlueKing/bk-bcs pull request #3256
Opened 2024-06-04 12:34 UTC by q15971095971

2024-06-07 03:46 UTC, luofann requested changes

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/add-label.vue
> +      <info width="14" height="14" class="icon-info" />
字体图标的尺寸用font-size控制

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/add-label.vue
> +      <plus width="12" height="12" class="add-label-plus" />
用css的font-size

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/add-label.vue
> +    <bk-popover
用v-bk-tooltips指令更方便

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/add-label.vue
> +  // import BkInput from 'bkui-vue/lib/input';
去掉不会用到的代码

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/add-label.vue
> +    labelArr.value.push(itemObj);
直接push一个object，不需要再通过变量转一层

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/file-option.vue
> +          <info width="14" height="14" class="icon-info" />
tooltip、font-size

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/file-option.vue
> +      <template #error>请先选择客户端密钥，替换下方示例代码后，再尝试复制示例</template>
错误message可以在rule里面定义，可以不用在模板处声明

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/file-option.vue
> +        </bk-popover>
tooltip、font-size

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/file-option.vue
> +      <template #error>请输入路径地址，替换下方示例代码后，再尝试复制示例</template>
rule.message

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/file-option.vue
> +  // import BkInput from 'bkui-vue/lib/input';
去掉不会用到的代码

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/key-selector.vue
> +    :no-match-text="'暂无可用密钥，如需添加或关联，可前往密钥管理'"
搜索无匹配结果也是用这个文案吗？

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/key-selector.vue
> +      <div :class="['key-option-item']">
class如果没有动态的情况，可以正常写

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/key-selector.vue
> +          <right-turn-line width="14" height="14" @click="flushData" class="flush-data-icon" />
font-size

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/key-selector.vue
> +  // }>();
去掉注释的内容

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/key-selector.vue
> +      credentialList.value = newData;
直接赋值好了

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/key-selector.vue
> +  const handleAppChange = (val: any) => {
- 方法名称尽量贴近准确含义
- `credentialList`已经有声明具体的类型，不要用`any`

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/key-selector.vue
> +    await loadCredentialList();
可以去掉async/await

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/service-selector.vue
> +          {{ localApp?.name }}
上面的v-if为啥没用`?` 操作符

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/service-selector.vue
> +  // }>();
去掉注释内容

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/index.vue
> +  import Selector from './components/service-selector.vue';
组件名尽量表意精确一点

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/index.vue
> +        </bk-menu>
这里两段bk-menu代码重复度很高，可以抽象一下
```vue
  <bk-menu :active-key="navList [0].val" @update:active-key="changeTypeItem">
    <bk-menu-item :need-icon="false" v-for="item in navList " :key="item.val"> {{ item.name }} </bk-menu-item>
  </bk-menu>
  ...
  const navList = computed(() => serviceType.value === 'file' ? fileTypeArr : kvTypeArr)
```

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/index.vue
> +      return KvExample;
这里的else可以去掉

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/index.vue
> +  const fileTypeArr = ref([
这个是固定的常量，不需要用`ref`

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/index.vue
> +  const kvTypeArr = ref([
不需要`ref`

2024-06-07 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/index.vue
> +    }
- watch里的逻辑为啥不写到`changeService `方法里
- if语句也可以简化为`?:`三目运算符

2024-06-13 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/components/head.vue
> +      navId === 'configuration-example'
```js
['service-all', 'client-statistics', 'client-search', 'configuration-example'].includes(navId)
```

2024-06-13 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/add-label.vue
> +  watch(labelArr.value, sendVal);
`script`的代码尽量按照以下顺序分区组织，每个部分间隔一个空行：
```md
1. 导入语句
2. hooks引入
3. props声明
4. emits声明
5. 常量声明
6. ref、reactive等属性声明
7. computed
8. watch、watchEffect
9. 生命周期
10. 方法
11. exposes声明
```

2024-06-13 03:46 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/add-label.vue
> +    <span class="label-span">标签</span>
模板中的中文记得最后都需要做国际化。

2024-06-17 09:02 UTC, luofann requested changes

2024-06-17 09:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/assets/exampleData/file-cmd.yaml
> +biz: {{ .Bk_Bscp_VariableBkBizId }}
变量名称最好统一一种格式，比如全小写加下划线的。现在包括驼峰、下划线、首字母大写有点乱了。

2024-06-17 09:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/components/code-editor/index.vue
> +      renderIndentGuides?: boolean;
增加的这些属性最好给个默认值吧，下面直接用了这些属性，又没有做是否有值的判断，可能会引起预期之外的问题。

2024-06-17 09:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/components/head.vue
> +    console.log(navId);
去掉调试语句

2024-06-17 09:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/code-preview.vue
> +  .abca1 {
这个class名称是会实际存在的吗？

2024-06-17 09:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/content/cmd-example.vue
> +    optionData.value = computed(() => {
组件事件回调里用computed，是什么场景？

2024-06-17 09:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/key-selector.vue
> +  const formError = inject<any>('formError');
类型声明不要使用`any`

2024-06-17 09:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/content/cmd-example.vue
> +    replaceVal.value = '';
计算属性的作用是返回一个计算后的状态，里面不要有赋值逻辑。

2024-06-17 09:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/content/container-example.vue
> +      <bk-button @click="copyExample" theme="primary" class="copy-btn">{{ $t('复制示例') }}</bk-button>
事件写在属性后面

2024-06-17 09:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/content/cmd-example.vue
> +    <form-option @option-data="getOptionData" ref="fileOptionRef" :directory-show="props.kvName !== 'kv-cmd'" />
事件写在最后面

2024-06-17 09:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/content/kv-example.vue
> +        <bk-button @click="copyExample" theme="primary" class="copy-btn">{{ $t('复制示例') }}</bk-button>
事件写在最后面

2024-06-17 09:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/content/kv-example.vue
> +    }).value;
去掉计算属性的用法

2024-06-17 09:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/content/kv-example.vue
> +        <div class="changeMethod">
css class名称统一用中划线，不用驼峰。

2024-06-17 09:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/form-option.vue
> +  const emits = defineEmits(['option-data']);
方法名称最好是按照 动词 + 名词的格式，表明一个动作，比如updateOptionData这种，现在看起来就像一个props属性，但其实又是个方法。

2024-06-17 09:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/key-selector.vue
> +    :class="['key-selector', { 'select-error': isError }]"
上面有个`key-selector`了

2024-06-17 09:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/key-selector.vue
> +        <div class="content" @click="router.push({ name: 'credentials-management' })">
这里建议新开页面打开

2024-06-17 09:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/key-selector.vue
> +        isError.value = true;
校验合法之后有将isError置为false的逻辑吗

2024-06-17 09:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/service-selector.vue
> +          {{ localApp?.name }}
上面用了，下面就没必要用了。

2024-06-17 13:29 UTC, q15971095971 commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/key-selector.vue
> +        isError.value = true;
![image](https://github.com/TencentBlueKing/bk-bcs/assets/30098481/fb541689-ef71-41bc-9419-c09ed9a4e343)
有的，当下拉框选中值后就会改回false

2024-06-26 09:40 UTC, luofann approved these changes

2024-06-26 09:44 UTC, AlkaidChan approved these changes

2024-06-26 09:45 UTC, merged