feat：新增dependabot alerts导出到表格方法
TencentBlueKing/bk-bcs pull request #3266
Opened 2024-06-07 07:22 UTC by LidolLxf

feat：新增dependabot alerts导出到表格方法

2024-06-17 12:41 UTC, adevjoe requested changes

2024-06-17 12:41 UTC, adevjoe commented on scripts/main.go
加个 readme 吧，token 怎么获取，怎么用

2024-06-18 07:45 UTC, adevjoe approved these changes

2024-06-19 09:59 UTC, ifooth approved these changes

2024-06-19 09:59 UTC, merged