feat：模板文件yaml 转表单，yaml 语法错误提示行数
TencentBlueKing/bk-bcs pull request #3291
Opened 2024-06-19 01:44 UTC by LidolLxf

feat：模板文件yaml 转表单，yaml 语法错误提示行数

2024-06-21 02:38 UTC, adevjoe requested changes

2024-06-21 02:38 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/handler/resource/render.go
> +	}
改到变量解析后检测 yaml 格式

2024-07-02 01:59 UTC, adevjoe approved these changes

2024-07-02 02:02 UTC, ifooth approved these changes

2024-07-02 02:02 UTC, merged