feat:分组管理增加跨页全选功能 --story=118110616
TencentBlueKing/bk-bcs pull request #3321
Opened 2024-06-29 06:30 UTC by q15971095971

2024-08-07 10:02 UTC, luofann requested changes

2024-08-07 10:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/api/template.ts
> + * @param no_set_specified 是否未指定套餐，此处固定传true
实际接口调用没有看到对应的参数

2024-08-07 10:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/api/template.ts
> + * @param no_set_specified: boolean, // 是否未指定套餐
修改下注释。

2024-08-07 10:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/components/across-check-table-tip.vue
> +      <template v-if="locale === 'zh-cn'">条数据</template>
这个没有做国际化？

2024-08-07 10:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/components/across-check-table-tip.vue
> +        <template v-if="locale === 'zh-cn'">条</template>
单位也需要国际化

2024-08-07 10:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/components/across-check-table-tip.vue
> +      <span class="checked-em" v-show="!(selectionsLength === dataLength)" @click="selectTypeChange">
`!(selectionsLength === dataLength)`这么判断是不是有点绕了？改成`selectionsLength < dataLength`更直观。

2024-08-07 10:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/components/across-check-table-tip.vue
> +      <template v-if="locale === 'zh-cn'">条数据</template>
国际化

2024-08-07 10:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/components/across-check-table-tip.vue
> +      <span class="checked-em" v-show="!(showSelectedLength === dataLength)" @click="selectTypeChange">
判断条件优化

2024-08-07 10:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/components/across-check-table-tip.vue
> +    },
以上所有的props类型声明，改成ts格式，具体写法参考其他文件。

2024-08-07 10:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/components/across-check.vue
> +  });
以上所有的props类型声明，改成ts格式，具体写法参考其他文件。

2024-08-07 10:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/components/across-check.vue
> +  const popover = ref<any>(null);
尽量避免用`any`声明类型，这里是什么原因会用到？

2024-08-07 10:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/components/across-check.vue
> +  const { value } = toRefs(props);
这里使用`toRefs`的目的是什么？props本来就是响应式的

2024-08-07 10:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/components/across-check.vue
> +  watch(value, (newV) => {
watch可以直接监听`props.value`

2024-08-07 10:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/components/across-checkbox.vue
> +  });
ts的写法

2024-08-07 10:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/utils/hooks/use-table-acrosscheck-fulldata.ts
> +  const selections = ref<any[]>([]);
这种不知道传入数据具体类型的应该用泛型来推导

2024-08-07 10:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/utils/hooks/use-table-acrosscheck-fulldata.ts
> +      arrowShow: arrowShow?.value,
- arrowShow可能不存在吗？如果是这样，可以在函数声明的时候给个默认值，使用的时候就不需要先做判断了。
- 这个变量命名也有点奇怪，字面意思是【显示箭头】？看后面的注释意思是用来标识是否提供全选功能的，所以变量命名要尽量精确，不好的命名对代码可读性有很大的负面作用。

2024-08-07 10:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/utils/hooks/use-table-acrosscheck-fulldata.ts
> +import { h, Ref, ref } from 'vue';
这个文件和use-table-acrosscheck.ts的绝大部份逻辑都一致，是不是可以抽象一层？

2024-08-07 10:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/groups/index.vue
> +  const filterFailureCurTableData = computed(() => tableData.value.filter((item) => item.released_apps_num! < 1));
上面两个变量命名不太规范，动词 + 名词看着是一个方法，但其实是数据

2024-08-07 10:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/groups/index.vue
> +    return (selections.value as IGroupItem[]).filter((item) => item.released_apps_num === 0).map((item) => item.id);
这里如果用泛型，应该就不需要手动声明类型了。

2024-08-07 10:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/scripts/list/script-list.vue
> +      state.filterDisableCount = Number(res.exclusion_count);
- 这个数据可以不写在store里吗？属性会有跨多层组件使用的情况？
- 注意写在store里的数据，父组件销毁的时候需要清空，不然再次挂载组件的时候，如果没有覆盖store里数据的逻辑，会导致异常情况。

2024-08-07 10:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/templates/list/package-detail/operations/add-configs/create-new-config/index.vue
> +        );
这个方法的参数可以简化吗，一般一个方法的参数超过5个就很难维护了。

2024-08-07 10:02 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/templates/list/package-detail/operations/move-out-from-pkg/batch-move-out-from-pkg-dialog.vue
> +      );
这个也是参数个数过多，对代码维护和扩展不友好。

2024-08-09 09:34 UTC, luofann approved these changes

2024-08-09 09:39 UTC, AlkaidChan approved these changes

2024-08-09 09:39 UTC, merged