feat: user-manager支持周期性地同步token到redis
TencentBlueKing/bk-bcs pull request #3333
Opened 2024-07-03 02:58 UTC by Maclon9573

2024-07-08 01:39 UTC, adevjoe requested changes

2024-07-08 01:39 UTC, adevjoe commented on install/conf/bcs-services/bcs-user-manager/bcs-user-manager.json.template
> +  "enable_token_sync": "${enableTokenSync}",
bool 值配置文件不需要加引号 `""`

2024-07-08 01:39 UTC, adevjoe commented on install/conf/bcs-services/bcs-user-manager/bcs-user-manager.json.template
> +  "enable_token_sync": "${enableTokenSync}",
参考 `install/conf/bcs-services/bcs-user-manager/container-start.sh` 启动脚本中设置一个默认值，防止 chart 没加参数的情况下，配置文件加载错误，导致程序起不来

2024-07-08 02:06 UTC, Maclon9573 commented on install/conf/bcs-services/bcs-user-manager/bcs-user-manager.json.template
> +  "enable_token_sync": "${enableTokenSync}",
已修改

2024-07-08 03:00 UTC, adevjoe approved these changes

2024-08-12 03:01 UTC, evanlixin approved these changes

2024-08-12 03:01 UTC, merged