feat: 模板文件部署 diff
TencentBlueKing/bk-bcs pull request #3346
Opened 2024-07-09 09:07 UTC by LidolLxf

feat: 模板文件部署 diff

2024-07-16 10:15 UTC, adevjoe requested changes

2024-07-16 10:15 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/action/template/helper.go
> +			continue
kind 为空，当前内容还是要展示，集群中置为空就可以

2024-07-16 10:15 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/action/template/helper.go
> +			return nil, err
报错不终止，previousContent 置为空或者展示错误，下面也相同

2024-07-17 08:34 UTC, adevjoe requested changes

2024-07-17 08:34 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/action/template/helper.go
> +	if err != nil {
error 的加个日志吧，同时注释下报错不影响 preview 接口返回

2024-07-17 08:57 UTC, adevjoe approved these changes

2024-07-17 09:58 UTC, ifooth approved these changes

2024-07-17 09:58 UTC, merged