fix: 配置示例全部优化项--bug=126865407
TencentBlueKing/bk-bcs pull request #3351
Opened 2024-07-10 01:03 UTC by q15971095971

2024-07-10 02:16 UTC, luofann requested changes

2024-07-10 02:16 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/index.vue
>      { name: t('命令行工具'), val: 'kv-cmd' },
这个可以直接改为`shell`吗

2024-07-10 02:16 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/add-label.vue
> +      }}</span>
换行格式优化下：
```vue
<span>
  {{ xxxx }}
</span>
```

2024-07-10 02:16 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/add-label.vue
> +  const validateKey = new RegExp(
这里变量的名称看着像是一个校验方法，但其实只是一个正则类型的变量，可以优化为：`keyValidateReg`。下面value的正则变量也是。

2024-07-10 02:16 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/add-label.vue
> +  const validateAll = computed(() => {
变量命名还是看着像方法。建议改为: `isAllValid`

2024-07-10 02:16 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/components/add-label.vue
> +  const validateAll = computed(() => {
声明的这个计算属性，只是在下面watch的回调里用到了，其实必要没有把它弄成计算属性。

2024-07-10 02:16 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/index.vue
> +    const scrollDom = document.querySelector('.example-main');
这里不要在`document`层级取查找dom元素，尤其是这种容易重复的classname，把范围到组件内。

2024-07-10 02:16 UTC, luofann commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/index.vue
> +    const scrollDom = document.querySelector('.example-main');
并且这个地方用`ref`不是更合适吗？

2024-07-10 02:22 UTC, q15971095971 commented on bcs-services/bcs-bscp/ui/src/views/space/client/example/index.vue
>      { name: t('命令行工具'), val: 'kv-cmd' },
文件型和键值型的命令行工具共用一个组件，但是内容有差异化，需要file-cmd/kv-cmd来区分

2024-07-11 01:51 UTC, luofann approved these changes

2024-07-11 02:30 UTC, AlkaidChan approved these changes

2024-07-11 02:30 UTC, merged