feat: 新增模板文件草稿
TencentBlueKing/bk-bcs pull request #3378
Opened 2024-07-16 09:40 UTC by LidolLxf

feat: 新增模板文件草稿

2024-07-16 10:05 UTC, adevjoe requested changes

2024-07-16 10:05 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/action/template/template.go
> +		CreateAt:      now.UTC().Unix(),
store 里面已经有了，不需要加上

2024-07-17 08:28 UTC, adevjoe requested changes

2024-07-17 08:28 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/action/template/template.go
> +		return "", errors.New("non draft template files require version")
这个提示国际化一下，信息改成 `version field required`

2024-07-17 08:28 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/action/template/template.go
> +	if req.GetIsDraft() && template.IsDraft {
这里如果之前是草稿态，放弃草稿态就不支持了，或者之前不是草稿态，变成草稿态也不支持。这里改成直接根据接口参数传入

2024-07-17 08:28 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/action/templateversion/templateversion.go
> +		updateTemplate["baseVersion"] = req.GetVersion()
版本也清空吧

2024-07-17 08:58 UTC, adevjoe approved these changes

2024-07-17 09:58 UTC, ifooth approved these changes

2024-07-17 09:58 UTC, merged