feat: helmctl diff预览部署增减有颜色标识及preview接口去掉不支持的参数
TencentBlueKing/bk-bcs pull request #3407
Opened 2024-07-26 08:42 UTC by LidolLxf

feat: helmctl diff预览部署增减有颜色标识及preview接口去掉不支持的参数

2024-07-29 08:37 UTC, adevjoe requested changes

2024-07-29 08:37 UTC, adevjoe commented on bcs-services/bcs-helm-manager/internal/actions/release/preview.go
> +	filtContent := map[string]struct{}{
使用黑名单，先过滤掉 `--force`

2024-07-29 08:37 UTC, adevjoe commented on bcs-services/bcs-helm-manager/internal/client/cmd/diff.go
> +var (
helmctl readme 文档更新下

2024-07-29 08:37 UTC, adevjoe commented on bcs-services/bcs-helm-manager/internal/client/cmd/diff.go
> +	releasePreview, err := c.Release().ReleasePreview(cmd.Context(), &req)
rollback diff 是当前 revision 和指定历史 revision 对比

2024-07-30 02:49 UTC, adevjoe approved these changes

2024-07-30 02:50 UTC, ifooth approved these changes

2024-07-30 02:50 UTC, merged