feat: 模板文件支持 Helm 语法模式
TencentBlueKing/bk-bcs pull request #3494
Opened 2024-09-05 09:48 UTC by LidolLxf

feat: 模板文件支持 Helm 语法模式

2024-09-19 08:34 UTC, adevjoe requested changes

2024-09-19 08:34 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +	string grammarMode = 6 [(grpc.gateway.protoc_gen_swagger.options.openapiv2_field) = {
templatefile 版本创建出来就已经有语法模式了，部署这里不用传

2024-09-19 08:34 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/action/template/template.go
> +	if req.GrammarMode == "Helm" {
语法模式放在 templatefile 里面，类似于 editFormat 一样，前端可以根据语法模式不同展现形式不同。
部署的时候自动从 templatefile 里面读取语法模式

2024-09-19 08:43 UTC, adevjoe requested changes

2024-09-19 08:43 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/action/template/template.go
> +	if req.GrammarMode == "Helm" {
改成 `RenderMode`

2024-09-23 03:08 UTC, adevjoe requested changes

2024-09-23 03:08 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/resource/constants/common.go
> +	// SimpleRenderMode 单一语法模式，默认
简单语法模式，使用字符串替换渲染

2024-09-23 03:08 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/action/template/template.go
> +	content, errRender := renderHelmTemplate(templates, req.GetValues())
非 helm 语法模式为什么也要用 helm 渲染

2024-10-09 08:33 UTC, adevjoe requested changes

2024-10-09 08:33 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/action/template/template.go
> +	content, errRender := renderHelmTemplate(templates, req.GetValues())
同上

2024-10-11 09:19 UTC, ifooth approved these changes

2024-10-11 09:19 UTC, merged