feat: 模板文件支持展示最新部署及版本列表兼容非语义化版本
TencentBlueKing/bk-bcs pull request #3517
Opened 2024-09-11 06:10 UTC by LidolLxf

feat: 模板文件支持展示最新部署及版本列表兼容非语义化版本

2024-09-13 08:22 UTC, tencentblueking-adm commented
[![CLA assistant check](https://bk-cla.bktencent.com:443/pull/badge/not_signed)](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-bcs?pullRequest=3517) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-bcs?pullRequest=3517) before we can accept your contribution.<br/>**7** out of **9** committers have signed the CLA.<br/><br/>:white_check_mark: penglongli<br/>:white_check_mark: LidolLxf<br/>:white_check_mark: Ambition9186<br/>:white_check_mark: Yuikill<br/>:white_check_mark: Maclon9573<br/>:white_check_mark: q15971095971<br/>:white_check_mark: AlkaidChan<br/>:x: v_czhicai<br/>:x: evanlixin<br/><hr/>**v_czhicai** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bk-cla.bktencent.com:443/check/TencentBlueKing/bk-bcs?pullRequest=3517) it.</sub>

2024-09-19 08:28 UTC, adevjoe requested changes
lint 问题处理一下

2024-09-19 08:28 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/action/template/template.go
> +		LatestVersion: req.GetVersion(),
改成 `LatestDeployVersion`

2024-09-19 08:28 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/action/templateversion/templateversion.go
> +		"latestVersion": req.Version,
db 字段名相应调整

2024-09-19 08:28 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/store/entity/templateversion.go
> +	LatestVersion string             `json:"latestVersion" bson:"-"`
LatestDeployVersion

2024-09-19 08:28 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/store/entity/templateversion.go
> +	LatestVersion string             `json:"latestVersion" bson:"-"`
这里没添加部署人

2024-09-19 08:28 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/action/template/template.go
> +		LatestVersion: req.GetVersion(),
部署人改成 `LatestDeployer`

2024-09-23 02:58 UTC, adevjoe requested changes

2024-09-23 02:58 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/action/templateversion/templateversion.go
> +	updateTemplate := entity.M{
这里是部署版本，不是最新版本，只在部署是更新 `latestDeployVersion` 和 `latestDeployer `

2024-10-09 08:29 UTC, adevjoe approved these changes

2024-10-09 08:35 UTC, ifooth approved these changes

2024-10-09 08:35 UTC, merged