feat: 资源视图表单 cronjob 表达式支持正则
TencentBlueKing/bk-bcs pull request #3540
Opened 2024-09-26 09:41 UTC by LidolLxf

feat: 资源视图表单 cronjob 表达式支持正则

2024-10-09 08:27 UTC, adevjoe requested changes

2024-10-09 08:27 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/resource/form/renderer/schema.go
> +		"scheduleValid": map[string]interface{}{
这个正则表达式写个单测吧，顺便把 lint 修下

2024-10-11 08:44 UTC, adevjoe approved these changes

2024-10-11 09:19 UTC, ifooth approved these changes

2024-10-11 09:19 UTC, merged