feat: bcs-task mysqlstore status index
TencentBlueKing/bk-bcs pull request #3594
Opened 2024-10-25 07:43 UTC by ifooth

2024-10-31 12:53 UTC, liuchenyiwork requested changes

2024-10-31 12:53 UTC, liuchenyiwork commented on bcs-common/common/task/metrics.go
> +		Buckets: []float64{1, 10, 30, 60, 60 * 5, 60 * 10, 60 * 30, 3600, 3600 * 2},
建议和task的桶数量保持一致

2024-10-31 12:53 UTC, liuchenyiwork commented on bcs-common/common/task/metrics.go
> +	}, []string{"task_type", "task_name", "executor"})
考虑到task_name内容不可控，建议去掉

2024-10-31 12:53 UTC, liuchenyiwork commented on bcs-common/common/task/metrics.go
> +	}, []string{"task_type", "task_name", "status"})
考虑到task_name内容不可控，建议去掉

2024-10-31 13:53 UTC, ifooth commented on bcs-common/common/task/metrics.go
> +		Buckets: []float64{1, 10, 30, 60, 60 * 5, 60 * 10, 60 * 30, 3600, 3600 * 2},
done

2024-10-31 13:53 UTC, ifooth commented on bcs-common/common/task/metrics.go
> +	}, []string{"task_type", "task_name", "executor"})
done

2024-10-31 13:53 UTC, ifooth commented on bcs-common/common/task/metrics.go
> +	}, []string{"task_type", "task_name", "status"})
done

2024-11-01 02:12 UTC, evanlixin approved these changes

2024-11-01 02:12 UTC, merged