feat: 新增获取模板文件关联labels接口
TencentBlueKing/bk-bcs pull request #3599
Opened 2024-11-08 09:43 UTC by LidolLxf

feat: 新增获取模板文件关联labels接口

2024-12-03 02:16 UTC, adevjoe requested changes

2024-12-03 02:16 UTC, adevjoe commented on bcs-services/cluster-resources/proto/cluster-resources/cluster-resources.proto
> +			get: "/clusterresources/v1/projects/{projectCode}/template/labels/{id}"
改成 `/clusterresources/v1/projects/{projectCode}/templates/{id}/labels`

2024-12-04 03:46 UTC, adevjoe requested changes

2024-12-04 03:46 UTC, adevjoe commented on bcs-services/cluster-resources/pkg/resource/form/parser/common.go
> +		if associateName != "" {
层级太多了，可以提前返回的提前返回

2024-12-05 02:44 UTC, ifooth approved these changes

2024-12-05 03:45 UTC, merged