feat: project-manager支持原生ns接口
TencentBlueKing/bk-bcs pull request #3612
Opened 2024-11-25 07:27 UTC by LidolLxf

feat: project-manager支持原生ns接口

2024-12-02 08:16 UTC, adevjoe approved these changes

2024-12-02 08:16 UTC, adevjoe commented on bcs-services/bcs-project-manager/internal/actions/namespace/shared/native-list.go
> +	nsList, err := client.CoreV1().RESTClient().Get().Resource("namespaces").SetHeader("Accept", accept).DoRaw(ctx)
这里只能列出项目的共享集群命名空间

2024-12-04 03:27 UTC, adevjoe requested changes

2024-12-04 03:27 UTC, adevjoe commented on bcs-services/bcs-project-manager/internal/actions/namespace/shared/native-list.go
> +	if req.GetProjectIDOrCode() != "-" {
这里可以提前返回，if 层级太多了

2024-12-04 03:27 UTC, adevjoe commented on bcs-services/bcs-project-manager/internal/util/namespace/namespace.go
> +		if shared && pom.Annotations != nil && pom.Annotations[constant.AnnotationKeyProjectCode] != projectCode {
这里应该是
```
if !shared  {
  continue
}
if pom.Annotations == nil {
  continue
}
if pom.Annotations[constant.AnnotationKeyProjectCode] != projectCode {
	continue
}
```

2024-12-04 03:31 UTC, adevjoe requested changes

2024-12-04 03:31 UTC, adevjoe commented on bcs-services/bcs-project-manager/internal/actions/namespace/shared/native-list.go
> +			mt, err = nsutils.FilterTableNamespaces(mt, true, project.ProjectCode)
这里都是共享集群，没必要传递共享集群标志

2024-12-05 02:44 UTC, ifooth approved these changes

2024-12-05 02:44 UTC, merged