feat: 共享集群支持查询集群下所有命名空间的release
TencentBlueKing/bk-bcs pull request #3657
Opened 2024-12-24 08:42 UTC by LidolLxf

feat: 共享集群支持查询集群下所有命名空间的release

2024-12-25 06:54 UTC, adevjoe requested changes

2024-12-25 06:54 UTC, adevjoe commented on bcs-services/bcs-helm-manager/internal/actions/release/listv1.go
> -	if cluster.IsShared && len(option.Namespace) == 0 {
要先获取命名空间列表，然后根据列表并发去获取 release

2025-01-14 07:18 UTC, adevjoe requested changes

2025-01-14 07:18 UTC, adevjoe commented on bcs-services/bcs-helm-manager/internal/component/project/project.go
> +	p, err := cli.Namespace.ListNamespaces(context.Background(), &bcsproject.ListNamespacesRequest{
这里的 context 可以传进来

2025-01-14 08:43 UTC, adevjoe approved these changes

2025-01-14 08:44 UTC, ifooth approved these changes

2025-01-14 08:45 UTC, merged